trigger:
- main

jobs:
- job: "Run_RobotFramework_Tests"
pool:
  vmImage: "windows-2022"
  strategy:
   matrix:
    Python37:
     python.version: "3.7"
     maxParallel: 1
    steps:
     - task: UsePythonversion@0
    inputs:
      versionSpec: "$(python.version)"
      architecture: "x64"
      -script: pip install robotframework robotframework-seleniumlibrary && npm install chromedriver
      displayName: "Install dependencies"
      -powershell: python -m robot --test "Valid Login" --suite "/.Web Tests.Tests.Valid Login"
