trigger:
- main

pool:
  vmImage: windows-latest
strategy:
  matrix:
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    rfbrowser init
  displayName: 'Install dependencies'

- script: |
    robot -d ./logs -x output-xunit.xml tests
  continueOnError: true
  displayName: 'Run UI Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'logs/output-xunit.xml'
  displayName: 'Publish Test Results'
